language: python
sudo: true
os:
  - linux
  - osx
python:
  - '2.7'
  - '3.4'
  - '3.5'
  - '3.6'
before_install:
  - .travis/before_install.sh
install:
  - python setup.py install
script:
  - sudo -E nosetests --with-coverage test/test_partner.py
  - nosetests --with-coverage test/test_server.py
  - nosetests --with-coverage test/test_client.py
  - nosetests --with-coverage test/test_util.py
after_success:
  - codecov
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aacaa796672a51d47850
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: FVgr37xYK0D1Hfag0KVJlsc5m4x1hf+T2vBLAKZWPCYNq2jEIzCGtMLNGmgHBVqydWHM3HkTJTYqlPyguxC/DYnmLSNL4L6YeG1EUWQ4Zgn/IqK55lb0Sns2Qn4moTN/q53Z6vMUMRS4frnycZLa3AETGAedv5qyR92r7yEzAJk=
  on:
    tags: true
