os:
  - linux
  - osx
language: python
python:
  - 2.7
  - 3.4
before_install:
  - ./travis-deps.sh
  - pip install -r test/requirements.txt --use-mirrors
install:
  - python setup.py install
script:
  - sudo -E nosetests test/test_partner.py
  - nosetests test/test_server.py
  - nosetests test/test_client.py
  - nosetests test/test_util.py
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aacaa796672a51d47850
    on_success: change
    on_failure: always
    on_start: false
deploy:
  provider: pypi
  user: gijzelaerr
  password:
    secure: TIIVgCj4hU9KP3Ku0kqq3++1YQDq+B7RCubg/iXZoFpUFSeFaK4G7WJtN5TCs+iyBQYjO7e/RST3PAFq13Ru66CqmlJ3ImCfIzJaZZ1oG5j6qmaTKiYnXqMGd8nMXCn6gc7CvI2q6OOUFSIrDRsFbo35BglX/8NUH525HX0t8xE=
  on:
    tags: true
