language:
 - objective-c
 - python
python:
  - '2.7'
  - '3.4'
before_install:
  - brew update
  - brew install snap7 python
  - pip install -r test/requirements.txt --use-mirrors
install:
  - sudo python setup.py install
script:
  - sudo -E nosetests test/test_partner.py
  - nosetests test/test_server.py
  - nosetests test/test_client.py
  - nosetests test/test_util.py
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/aacaa796672a51d47850
    on_success: change
    on_failure: always
    on_start: false
