language:
 - objective-c
 - python
python:
  - '2.7'
before_install:
  - brew update
  - brew install snap7 python
  - pip install -r test/requirements.txt --use-mirrors
install:
  - sudo python setup.py install
script:
  - sudo nosetests test/test_partner.py
  - sudo nosetests test/test_server.py
  - nohup sudo snap7/bin/snap7-server.py &
  - nosetests test/test_client.py


